### ISSUE TITLE
Remove Mojo::Transaction::success

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1266]
The `success` method has been replaced with [result](https://mojolicious.org/perldoc/Mojo/Transaction#result) and [error](https://mojolicious.org/perldoc/Mojo/Transaction#error). https://github.com/mojolicious/mojo/commit/a443003fad4e0d785f16047fd131d6b18771610e The deprecation will be active until the next major release.

**Comment by pscott-au** [comment]
ok so in my dependent package I should be examining the code() result and not relying on the success method I'm guessing.

**Comment by kraih** [comment]
`if !$tx->error` is the same as `if $tx->success`.

**Comment by kraih** [comment]
Done, as part of the 9.0 branch.

**Comment by jonmz** [comment]
@kraih I came across this year-old issue to find out that `is_success` no longer works because I followed the code example on https://docs.mojolicious.org/Mojo/Transaction#result which still advertises `is_success` (and `is_error`) and thus no longer works. Would you mind updating the documentation accordingly?
