### ISSUE TITLE
Extending the Mojo::Promise API

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1310]
This comes up a lot on IRC, so i'll open this issue to collect ideas and votes for extensions to the [Mojo::Promise API](https://metacpan.org/pod/Mojo::Promise). So far we have limited the API mostly to what [JavaScript Promises](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) contain, which is not much at all. The small API does have the advantage that it is easy to learn, but very often Mojolicious users now end up making their own `Mojo::Promise::Role::*` extensions or even switching to [Future](https://metacpan.org/pod/Future) for more features. So, what are the most commonly used features that you would like to see added?

**Comment by kraih** [comment]
Personally, i very much like [bluebird promises](http://bluebirdjs.com/docs/api-reference.html) and there are two features i would like to see added. A [timeout](http://bluebirdjs.com/docs/api/timeout.html) and a [map](http://bluebirdjs.com/docs/api/promise.map.html) method.
```perl
# The timeout method would create a promise that rejects in 5 seconds with the error "Timeout!"
Mojo::Promise->race($promise1, $promise2, Mojo::Promise->timeout(5, 'Timeout!'))->then(sub {...});

# The map method would allow for 5 async operations to run at the same time here
Mojo::Promise->map(\@urls, sub { $url->get_p($_) }, {concurrency => 5})->then(sub {...});
```

**Comment by Grinnz** [comment]
Some more options could come from the available convergent future constructors from Future (`wait_any` is analogous to Mojo::Promise `race`, and `needs_all` is analogous to Mojo::Promise `all`). `wait_all` would be problematic because it unconditionally succeeds with the component promises and relies on being able to introspect the results, so I won't propose an analogue here.

`needs_any` would be similar to the current `all`, but acts in the opposite manner. It resolves immediately with the first promise that resolves, or rejects once all promises have rejected. The use case would be similar to `race` but when you want to try each promise until one is successful.

    Mojo::Promise->needs_any(
      $ua->get_p('http://mirror1.com/foo'),
      $ua->get_p('http://mirror2.com/foo'),
    )->then(sub { ... })->catch(sub { ... });

The name should of course be something better matching the existing API.

**Comment by niczero** [comment]
I like 'any' but I'm thinking it would be more useful to see the first exception rather than the last.  The first exception is more likely to be a hard failure (eg unrecognised username) while the last exception is more likely to be a soft failure (eg connection timeout).

**Comment by kraih** [comment]
I suppose `Mojo::Promise->timeout` and `Mojo::Promise->map` have been accepted judging by the number of votes. And `Mojo::Promise->get` might pass the vote based on the fact that Mojolicious itself already [uses the pattern](https://github.com/mojolicious/mojo/blob/169f2aead8a59b5a7f3e74976d07e04a22b31185/lib/Mojolicious/Command/eval.pm#L21-L25).

**Comment by kraih** [comment]
Looks like this this issue is over.
