### ISSUE TITLE
Installation Fail  in Windows/msys2 after adding lstat method

### ISSUE THREAD

**Issue by yuki-kimoto** [mojolicious/mojo#1340]
The following test fail in Windows/msys2 after adding lstat method.

```
# t/mojo/file.t

# Lstat
$dir = tempdir;
my $orig = $dir->child('test.txt')->spurt('');
my $link = $orig->sibling('test.link');
SKIP: {
  skip 'symlinks unimplemented', 2 unless eval { symlink $orig, $link };
  is $link->stat->size,    0, 'target file is empty';
  isnt $link->lstat->size, 0, 'link is not empty';
}
```

This failure can be avoided by the following settings

```
export MSYS=winsymlinks
```

**Comment by CandyAngel** [comment]
I've [created a wiki page](https://github.com/mojolicious/mojo/wiki/Installation-under-msys2) mentioning this issue and the workaround. Thanks for sharing them.

 I included some other information I found while researching the issue so if you could check it over, that would be appreciated.

I'll leave this issue open for now so I can investigate into an appropriate fix in Mojolicious, if any.

**Comment by yuki-kimoto** [comment]
thnak you for creating wiki page

**Comment by CandyAngel** [comment]
From what I understand, this is actually an issue in msys2's link emulation, as it shouldn't be possible to have a link with "zero" content (it should contain the target identifier, usually its path).

As the test is testing for correct behaviour and this seems to be an issue with the environment, it's unlikely a workaround will be added to Mojolicious. Perhaps consider contacting the msys2 developers and ask them improve the emulation?

If you are happy with the workaround, please close this issue. If you want to keep it open while you speak to the msys2 developers, just let me know. I'll close in a couple of weeks otherwise.

Thanks for the report regardless!

**Comment by yuki-kimoto** [comment]
> it's unlikely a workaround will be added to Mojolicious

OK.

**Comment by CandyAngel** [comment]
I'm going to go ahead and close this as there has been no expression to keep it open and workarounds for environment bugs are rarely added to Mojolicious.
