### ISSUE TITLE
Route of / will match //

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1347]
* Mojolicious version: 8.15
* Perl version: 5.28.0
* Operating system: Ubuntu 18.04.1 LTS (on Windows Subsystem for Linux on Windows 10 Pro Version 1903)

### Steps to reproduce the behavior
Create a route to `/`:

```
use Mojolicious::Lite;

get '/' => { text => 'Hi, Mojo!' };

app->start;
```

And go to [http://localhost:3000//](http://localhost:3000//).

### Expected behavior
Page should return a 404 error.

### Actual behavior
Page loads the route for one slash.

If this is expected behavior, feel free to close! It seemed strange to me, so I filed this. 

Also, this doesn't seem to work with three or more slashes, and it doesn't seem to work on other routes besides `/`. For example, a route `/about` won't match `/about//`.

**Comment by jberger** [comment]
I don't believe that `//` is markedly different from `/`. I wouldn't necessarily expect a 404. In a terminal `cd .//` takes you to the same place (the current working directory) as `cd .` and `cd ./`. In chrome and curl (and `mojo get`), visiting `https://github.com/mojolicious/mojo//` takes you to the same result as `https://github.com/mojolicious/mojo/` or `https://github.com/mojolicious/mojo`; it doesn't even redirect or otherwise cleanup the path.

Given that the "living standard" of the web seems to allow multiple slashes, I think we'd need some pretty compelling standards/specs to prevent that behavior. If you find that, please feel free to reopen this ticket or open a new one.

**Comment by shadowcat-mst** [comment]
I think it boils down to "a single trailing slash isn't paid attention to, because *shrug*" - so the /foo// case doesn't get caught by that, but / versus // and /foo versus /foo/ do

**Comment by srchulo** [comment]
@jberger Thanks for the response! I think those are good points and make sense.

One thing I will point out is that it seems like there is some inconsistency in that `//` will match `/`, but `/about//` will not match `/about/` or `/about`. And multiple trailing slashes will fail on `/`, which is not the case for `https://github.com/////`. So I'm not sure that Mojolicious is consistent with what may be the "living standard" of the web.

All of that being said, I do think this is very minor and not that important. I just wanted to bring it up in case this wasn't the intended behavior.
