### ISSUE TITLE
Feature Request: Add lines to Mojo::File which returns a Mojo::Collection

### ISSUE THREAD

**Issue by srchulo** [mojolicious/mojo#1392]
I find myself doing this a lot:

```
my @lines = split "\n", path($filename)->slurp;
```

I think it would be great if there was a method named something like `lines` that returned a [Mojo::Collection](https://metacpan.org/pod/Mojo::Collection) of the lines in a file. This would also be useful because a lot of times I find myself doing `map` or `grep` or a `foreach` loop, and a `Mojo::Collection` would make all of these convenient.

**Comment by kiwiroy** [comment]
My version is

```perl
my $lines = c(split "\n" => path($file)->slurp);
# often followed
my $hashes = $lines->tap(sub {$cols = [split "\t", shift @$_]})
    ->map(sub { my %t; @t{@$cols} = split "\t"; \%t; });
```

**Comment by kraih** [comment]
The problem with adding a `->lines` method is that we suddenly have to care about encoding.

**Comment by Tekki** [comment]
> The problem with adding a `lines` method is that we suddenly have to care about encoding.

```
# today
my @lines = split "\n", decode('UTF-8', path($filename)->slurp);

# 'a possible future'
my $content = path($filename)->slurp('UTF-8');
my @lines = path($filename)->lines('UTF-8');
```

**Comment by jhthorsen** [comment]
Could it be possible for a more generic method that takes an argument to split on, and defaults to `$/`?

**Comment by CandyAngel** [comment]
If file parsing was being added into Mojo::File, wouldn't it be better as some sugar around roles, rather than discrete methods? Otherwise we could end up with all sorts (lines, decompress, csv, etc.).

Perhaps something like adding in a base 'parse' method, which takes a class and arguments and uses with_roles and delegation?

```
sub parse {
  my ($self, $class, @args) = @_;
  return unless defined $class;
  return $self->with_roles($class)->parse(@args);
}
```

then

```
my $lines = path('fortune.txt)->parse('+Lines', qr/\R/);
my $csv = path('data.csv')->parse('+CSV', {sep_char => "|"});
my $json = path('cache.json')->parse('+JSON');
```

(but, you know, without the obvious implementation issue :P)

This can allow all sorts of configurable parsing behaviours, such as avoiding reading huge files into memory..

`path('data.csv')->parse('+CSV', {cb => sub { $self->handle_csv_row(@_) }});`

I do have something like this for code at $work, where files exported from one of the systems can be a variety of formats and I use roles to contain the parsing code for each format.

**Comment by kraih** [comment]
This should be explored with roles on CPAN before we consider additions to `Mojo::File` itself.
