### ISSUE TITLE
:scope selector for Mojo::DOM

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1405]
We have an [almost finished branch](https://github.com/mojolicious/mojo/compare/scope_only) for [scope selectors](https://www.w3.org/TR/selectors-4/#the-scope-pseudo) already. There is just one problem, we have not yet found a way to make sibling combinators work with `:scope`.
```perl
# TODO: Make :scope work with sibling combinators
#is $dom->find('foo')->[1]->at(':scope ~ foo')->text, 'B', 'right result';
```
It's a bit of a brain teaser.

**Comment by Eckankar** [comment]
I'll just relay my thoughts from IRC on here for posterity.

https://metacpan.org/release/Mojolicious/source/lib/Mojo/DOM/CSS.pm#L231 trims out the current subtree, but the answer to `':scope ~ foo'` doesn't reside inside of that.

It feels like the problem could be solved by deciding on the queue to search through on a group-by-group basis. If the group mentions `:scope` anywhere in the selector, search from the root. Otherwise, search the subtree as is currently done.

**Comment by kraih** [comment]
@Eckankar Yes, that would seem reasonable.

**Comment by Eckankar** [comment]
I'll take a look at if I can get something working to do this.

**Comment by kraih** [comment]
The feature has been added.
