### ISSUE TITLE
Cover Test::Mojo methods with real tests

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1460]
All the test methods in `Test::Mojo` don't currently have real test coverage. They are just used in the Mojo test suite, but failures for example are never tested. So we need to find a clean way to test all of them.

Some possible solutions i could think of would be adding an event emitter or a public method like `_test` that can be temporarily overloaded. But whatever we choose it should look reasonably clean.

**Comment by kraih** [comment]
This is currently a blocker for #1459.

**Comment by kraih** [comment]
Since it would require more of an intercept feature, perhaps `_test` should just be an attribute.
```perl
my $t = Test::Mojo->new('TestApp');
$t->test(sub {
  my ($self, $name, @args) = @_;
  local $Test::Builder::Level = $Test::Builder::Level + 2;
  return $self->success(!!Test::More->can($name)->(@args));
});
...
```

**Comment by jberger** [comment]
We have talked before about possibly using the new Test2 functionality in tests and that has been largely abandoned because we'd need to depend on non-core Test2::Suite to get what we want. Thats said, as long as we can depend on a version of Test::More that includes the core Test2 that is mentioned here, https://metacpan.org/pod/Test2::API#TESTING-YOUR-TOOL

**Comment by kraih** [comment]
Feature has already been added.
