### ISSUE TITLE
Mojo::Promise's all() method cannot handle an empty array

### ISSUE THREAD

**Issue by davehayes** [mojolicious/mojo#1505]
* Mojolicious version: 8.29
* Perl version: 5.26
* Operating system: FreeBSD 11.3

### Steps to reproduce the behavior
```
> perl -MMojo::Promise -e 'Mojo::Promise->all();'
Can't call method "clone" on an undefined value at /usr/local/lib/perl5/site_perl/Mojo/Promise.pm line 124
```

### Expected behavior
I would expect this would do nothing, since there are zero promises. Technically, all of them have resolved even if the promise count is zero. 

### Actual behavior
This dies.

**Comment by Grinnz** [comment]
This was previously discussed in https://github.com/mojolicious/mojo/issues/1275. The problem is that promises require an event loop to resolve, even if they resolve instantly it is deferred, that is the Promises/A+ specification. The all method uses the first promise passed to it to know which event loop to defer to, with no promises it does not have that information.

**Comment by davehayes** [comment]
Understood. Thanks for the pointer to the discussion.
