### ISSUE TITLE
Cookbook example for Envoy deployment

### ISSUE THREAD

**Issue by kraih** [mojolicious/mojo#1543]
With Nginx going out of fashion we should add an example for how to use [Envoy](https://www.envoyproxy.io) as a reverse-proxy with Mojolicious to the [cookbook](https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Nginx).

**Comment by daleif** [comment]
I don't always keep up with things. Is it listed somewhere that nginx is going out of fashion?

**Comment by poizon** [comment]
Dropbox going to Envoy. 😂

**Comment by zakame** [comment]
I think deriving from https://www.envoyproxy.io/docs/envoy/latest/start/sandboxes/front_proxy could be a good start for this, let me check this out and make some notes...

OTOH since Envoy is normally deployed as a Docker container (https://www.envoyproxy.io/docs/envoy/latest/install/building#install-binaries) I think the scope of this has to be expanded towards deploying Mojo apps under container environments as well, since the current cookbook docs do not talk about it, only about general strategy about deploying under a reverse-proxy.

**Comment by zakame** [comment]
https://gist.github.com/zakame/eb48bbecd2f74e9bb2463687ba8d611b shows a very "minimal" reverse-proxy-only example.
